name: wikontext
channels:
- defaults
- conda-forge
# - ericmjl
dependencies:
- python=3.6
- scipy
- requests
- flask
- flask-cors
- gunicorn
- pyopenssl
- nltk
- scikit-learn
- gensim
# - bokeh
- html5lib
- beautifulsoup4
- Cython
- pip:
  - fasttext
  # - mwparserfromhell
  # - htmlst
