name: wikontext
channels:
- defaults
- conda-forge
# - ericmjl
dependencies:
- python=3.6
- scipy
- requests
- flask
- flask-cors
- nltk
- scikit-learn
# - bokeh
- html5lib
- beautifulsoup4
# - pip:
  # - mwparserfromhell
  # - htmlst
